// English interstitial learning cards: 250 final accepted entries.
// Personal review v015: accepted expansion decisions through C150 applied: 2026-08-14.
// Entries 1–192 preserve the verified v014 game order; entries 193–250 follow expansion acceptance rank.
// Rebuilt candidates C151–C450 remain pending and are not included.
// Schema: {term, en, zh, emoji}.
window.LANG_TIPS_ENGLISH_IELTS = [
  {term:"Move the needle", en:"To produce a noticeable or measurable change in a result.", zh:"使結果出現明顯或可衡量的改變。", emoji:"📈"},
  {term:"Put a pin in something", en:"To pause a topic or idea with the intention of returning to it later.", zh:"暫停討論某個話題或想法，打算之後再回來處理。", emoji:"📌"},
  {term:"Throw a wrench in the works", en:"To cause an unexpected problem that disrupts a plan or process.", zh:"製造突發問題，打亂原本的計畫或進程。", emoji:"🔧"},
  {term:"In the weeds", en:"Overwhelmed by work or problems, or so buried in details that the main issue is hard to see. This is informal US English.", zh:"被工作或問題壓得難以應付，或鑽進瑣碎細節而看不清重點；屬美式非正式用語。", emoji:"🌿"},
  {term:"Move the goalposts", en:"To unfairly change the rules or requirements after a process has begun, making success harder.", zh:"在事情開始後不公平地改變規則或達標條件，讓別人更難成功。", emoji:"🥅"},
  {term:"Kick the can down the road", en:"To postpone dealing with a problem or decision, usually without solving it.", zh:"把問題或決定往後拖，卻沒有真正解決。", emoji:"🥫"},
  {term:"Back to square one", en:"Back at the starting point after an attempt has failed or made no progress.", zh:"因嘗試失敗或沒有進展，只好回到起點重新開始。", emoji:"🔄"},
  {term:"Not have a leg to stand on", en:"To have no facts, evidence, or valid argument supporting your position.", zh:"沒有事實、證據或合理論點支撐自己的立場；完全站不住腳。", emoji:"🦵"},
  {term:"Learn the ropes", en:"To learn the basic procedures and practical details of a job or activity.", zh:"學會一項工作或活動的基本流程與實務細節。", emoji:"🪢"},
  {term:"Draw a line in the sand", en:"To establish a firm limit or position beyond which you will not compromise or allow someone to go.", zh:"劃定不再退讓、也不容他人越過的明確界線。", emoji:"🏖️"},
  {term:"In a nutshell", en:"In a very brief and clear form, using only the most important information.", zh:"用非常簡短清楚的方式說明最重要的內容；簡而言之。", emoji:"🌰"},
  {term:"Throw the baby out with the bathwater", en:"To get rid of something valuable while trying to remove what is unwanted or harmful.", zh:"在剔除不要或有害的部分時，連有價值的部分也一併丟掉；因噎廢食。", emoji:"🛁"},
  {term:"A rule of thumb", en:"A practical general guideline that is useful but not exact in every situation.", zh:"實用但不一定適用於所有情況的大致原則；經驗法則。", emoji:"👍"},
  {term:"Fall through the cracks", en:"To be overlooked, forgotten, or left unaddressed when people or a system fail to notice or deal with someone or something.", zh:"因人們或制度未注意、未處理，導致某人或某事被忽略或遺漏。", emoji:"🕳️"},
  {term:"Wrap your head around something", en:"To succeed in understanding something complicated, unfamiliar, or surprising.", zh:"設法理解複雜、陌生或令人難以置信的事情。", emoji:"🧠"},
  {term:"Touch base", en:"To make brief contact with someone in order to exchange information or give an update.", zh:"與某人簡短聯絡，以交換資訊或更新近況。", emoji:"📞"},
  {term:"Open a can of worms", en:"To create a complicated set of problems by raising or dealing with an issue.", zh:"因提出或處理某個問題，而引發一連串複雜麻煩。", emoji:"🪱"},
  {term:"Put the cart before the horse", en:"To do things in the wrong order by dealing with a later step before the necessary earlier one.", zh:"把事情的先後次序顛倒，在必要的前一步尚未完成前就先處理後面的步驟；本末倒置。", emoji:"🐎"},
  {term:"Shoot yourself in the foot", en:"To damage your own interests through a foolish decision or action.", zh:"因愚蠢的決定或行動損害自己的利益；自找麻煩。", emoji:"🦶"},
  {term:"Get the hang of it", en:"To begin to understand how to do something after some practice.", zh:"經過一些練習後，開始掌握做某事的方法。", emoji:"🧠"},
  {term:"Meet someone halfway", en:"To reach agreement by accepting part of what the other person wants.", zh:"各自讓步一部分，以便與對方達成共識。", emoji:"🤝"},
  {term:"Cut corners", en:"To save time or money by skipping important steps, often causing lower quality or risk.", zh:"為節省時間或金錢而省略重要步驟，往往造成品質下降或風險。", emoji:"✂️"},
  {term:"Your mileage may vary", en:"Used to say that another person’s experience or results may differ from yours. This is informal.", zh:"表示別人的體驗或結果可能與自己不同；屬非正式用語。", emoji:"🚗"},
  {term:"Stick your neck out", en:"To take a personal risk by supporting someone, expressing an opinion, or trying something.", zh:"為支持某人、表達意見或嘗試某事而承擔個人風險。", emoji:"🦒"},
  {term:"On a shoestring", en:"With only a very small amount of money available. This is informal English.", zh:"在可用資金極少的情況下；以極低預算。屬非正式用語。", emoji:"👟"},
  {term:"Scrape the bottom of the barrel", en:"To use the worst people, ideas, or resources because all the better ones have already been exhausted.", zh:"因較好的選擇都已用盡，只好採用最差的人、點子或資源。", emoji:"🛢️"},
  {term:"Work like a charm", en:"To work perfectly or solve a problem very effectively.", zh:"運作得非常順利，或極有效地解決問題。", emoji:"✨"},
  {term:"Run a tight ship", en:"To manage an organization in a strict, orderly, and efficient way.", zh:"以嚴謹、有秩序且有效率的方式管理組織。", emoji:"🚢"},
  {term:"Live within your means", en:"To spend no more money than you can afford from your income or resources.", zh:"量入為出，不花超過自己收入或資源所能負擔的金額。", emoji:"🏠"},
  {term:"Bide your time", en:"To wait patiently for the right opportunity to act.", zh:"耐心等待最適合採取行動的時機。", emoji:"⏳"},
  {term:"Let the dust settle", en:"To wait until a confusing, emotional, or rapidly changing situation becomes calmer and clearer.", zh:"等待混亂、情緒化或快速變動的情勢平靜下來、變得更清楚。", emoji:"🌫️"},
  {term:"Foot the bill", en:"To pay for something, especially when the cost is large or shared by a group.", zh:"支付費用，尤其指金額較大或原本由多人共同負擔的帳單。", emoji:"🧾"},
  {term:"Keep it in your back pocket", en:"To keep an idea, fact, or resource in reserve so it can be used when needed.", zh:"把點子、資訊或資源保留作為後手，需要時再拿出來。", emoji:"👖"},
  {term:"Wiggle room", en:"Freedom to change details, reconsider a decision, or act flexibly if circumstances change. This is informal English; “wriggle room” is also used, especially in the UK.", zh:"可在情況改變時調整細節、重新考慮或彈性行動的迴旋餘地；屬非正式用語，英式也可說 wriggle room。", emoji:"↔️"},
  {term:"Hedge your bets", en:"To avoid committing to one choice so that you reduce the risk of being wrong or losing.", zh:"不把希望全押在單一選擇上，以降低判斷錯誤或損失的風險。", emoji:"🎲"},
  {term:"Spread yourself too thin", en:"To take on so many different activities or responsibilities that you cannot give enough time or attention to any of them.", zh:"同時承擔太多活動或責任，以致每一件事都分不到足夠的時間或心力。", emoji:"🍞"},
  {term:"A judgment call", en:"A decision made by personal judgment because no rule or available evidence gives a definite answer.", zh:"因沒有規則或現有證據能提供明確答案，只能憑個人判斷做出的決定。", emoji:"⚖️"},
  {term:"With the benefit of hindsight", en:"With the clearer understanding that becomes available only after an event has happened.", zh:"事情發生後才取得的較清楚理解；事後回頭看。", emoji:"🔙"},
  {term:"Err on the side of caution", en:"To choose the safer course when uncertain, even if it may be more cautious than necessary.", zh:"在不確定時選擇較安全的做法，即使可能比實際需要更謹慎。", emoji:"⚠️"},
  {term:"A leap of faith", en:"An act of believing or committing to something despite lacking proof or certainty.", zh:"儘管缺乏證明或把握，仍選擇相信或投入；信念的一躍。", emoji:"🪽"},
  {term:"Play devil’s advocate", en:"To argue for an opposing position, whether or not you believe it, in order to test an idea or stimulate discussion.", zh:"不論自己是否認同，刻意替相反立場辯護，以檢驗想法或激發討論。", emoji:"😈"},
  {term:"Take stock", en:"To pause and carefully assess a situation, your resources, or your progress before deciding what to do next.", zh:"先停下來仔細評估情勢、資源或進度，再決定下一步。", emoji:"📦"},
  {term:"Split the difference", en:"To resolve a disagreement by choosing a point or amount halfway between the two sides’ positions.", zh:"選擇雙方立場或金額的中間點來解決歧見；折衷各讓一半。", emoji:"➗"},
  {term:"Know the drill", en:"To already know the usual procedure and what you are expected to do. This is informal.", zh:"已經熟悉慣常流程，也知道自己該做什麼；屬非正式用語。", emoji:"🛠️"},
  {term:"Pay through the nose", en:"To pay far more than a fair or reasonable price for something.", zh:"為某物付出遠高於公平或合理行情的價格。", emoji:"👃"},
  {term:"A zero-sum game", en:"A situation in which one side can gain only if another side loses an equivalent amount.", zh:"一方必須以另一方遭受同等損失為代價才能獲利的局面；零和賽局。", emoji:"⚖️"},
  {term:"A self-fulfilling prophecy", en:"A belief or prediction that helps cause itself to become true because people act as if it already is true.", zh:"某種信念或預測因人們把它當真並據此行動，反而促使它成真；自我實現的預言。", emoji:"🔮"},
  {term:"Feast or famine", en:"A pattern in which there is either far too much of something or far too little, with no stable middle ground.", zh:"某事物不是多得過頭就是少得可憐、完全沒有穩定中間狀態的模式；時而盛宴、時而饑荒。", emoji:"🍽️"},
  {term:"Make-or-break", en:"So important that it will determine whether something succeeds or fails.", zh:"重要到足以決定某件事成敗的。", emoji:"⚖️"},
  {term:"Sweep it under the rug", en:"To hide or ignore a problem instead of dealing with it.", zh:"把問題掩蓋或置之不理，而不真正處理。", emoji:"🧹"},
  {term:"Come out of left field", en:"To appear, happen, or be said unexpectedly, with little apparent connection to what came before. This is mainly US English.", zh:"某件事毫無預警地出現、發生或被說出口，而且與先前內容看似沒有關聯；主要為美式用法。", emoji:"⚾"},
  {term:"Break the ice", en:"To make people feel more relaxed and comfortable when they first meet or begin talking.", zh:"讓初次見面或剛開始交談的人放鬆下來，打破尷尬。", emoji:"🧊"},
  {term:"Not get a word in edgewise/edgeways", en:"To be unable to speak because someone else is talking continuously. US English uses “edgewise”; UK English uses “edgeways.”", zh:"因為別人不停說話而完全插不上嘴。美式用 edgewise；英式用 edgeways。", emoji:"🗣️"},
  {term:"Not bat an eye", en:"To show no surprise or worry when something unexpected happens. US English commonly uses “eye”; UK English uses “eyelid.”", zh:"遇到出乎意料的事情仍毫不驚訝、擔心或動搖。美式常用 eye；英式用 eyelid。", emoji:"😐"},
  {term:"Hit the nail on the head", en:"To describe a problem or answer a question exactly and correctly.", zh:"精準說中問題核心，或完全答對。", emoji:"🔨"},
  {term:"Muddy the waters", en:"To make an issue more confused, complicated, or difficult to understand.", zh:"把問題攪得更混亂、更複雜或更難理解。", emoji:"🌫️"},
  {term:"Not hold water", en:"If an argument, explanation, or story does not hold water, it is not believable or cannot withstand scrutiny.", zh:"形容論點、解釋或說法不可信，經不起推敲，站不住腳。", emoji:"💧"},
  {term:"Get the wrong end of the stick", en:"To misunderstand a situation or something that someone has said. This is especially common in British English.", zh:"誤解某個情況或別人所說的話；尤見於英式英語。", emoji:"🪵"},
  {term:"Beat around the bush", en:"To avoid talking directly about the main point, often because it is difficult or embarrassing.", zh:"因為困難或尷尬而迴避直接談論重點；拐彎抹角。", emoji:"🌳"},
  {term:"An echo chamber", en:"An environment in which people mainly encounter opinions and information that reinforce their existing beliefs, while opposing views are excluded or dismissed.", zh:"人們主要只接觸強化既有信念的資訊與意見，而反方觀點則被排除或否定的環境；回音室。", emoji:"🔊"},
  {term:"Cut to the chase", en:"To stop discussing unimportant details and deal directly with the main point.", zh:"停止討論不重要的細節，直接切入重點。", emoji:"🎯"},
  {term:"Give it a wide berth", en:"To deliberately avoid someone or something because they may be unpleasant, dangerous, or troublesome.", zh:"因為某人或某事可能令人不快、危險或麻煩，而刻意保持距離、避得遠遠的。", emoji:"↔️"},
  {term:"Strike a chord", en:"To cause someone to feel a strong sense of recognition or emotional connection.", zh:"引起某人強烈共鳴，讓對方覺得深有同感。", emoji:"🎸"},
  {term:"Hear me out", en:"To listen to everything someone wants to say before judging or responding.", zh:"在判斷或回應前，先把對方想說的話完整聽完。", emoji:"👂"},
  {term:"A heads-up", en:"Advance information or a warning that gives you time to prepare.", zh:"讓人能事先準備的預告、提醒或警示。", emoji:"📢"},
  {term:"Shoot from the hip", en:"To speak or act quickly and bluntly without taking time to think carefully.", zh:"沒有仔細思考便迅速而直率地發言或行動。", emoji:"🤠"},
  {term:"Keep me posted", en:"To continue giving someone the latest information about a situation.", zh:"持續向某人提供某件事的最新消息。", emoji:"📲"},
  {term:"Fill me in", en:"To give someone the information they need about a situation they do not fully know.", zh:"把某人尚未完全掌握的情況告訴對方，使其了解。", emoji:"📝"},
  {term:"Face the music", en:"To accept criticism or unpleasant consequences for something you have done.", zh:"為自己做過的事接受批評或不愉快的後果。", emoji:"🎵"},
  {term:"Let the cat out of the bag", en:"To reveal a secret, often accidentally or earlier than intended.", zh:"無意間或比預定時間更早洩露祕密。", emoji:"🐈"},
  {term:"Spill the beans", en:"To reveal secret information, sometimes after being persuaded or pressured.", zh:"透露祕密資訊，有時是在被勸說或施壓之後說出。", emoji:"🫘"},
  {term:"Dance around the issue", en:"To avoid addressing the central or difficult point directly.", zh:"刻意繞開核心或棘手的問題，不直接面對。", emoji:"💃"},
  {term:"Bite my tongue", en:"To stop yourself from saying something that you want to say.", zh:"忍住原本想說出口的話。", emoji:"👅"},
  {term:"See eye to eye", en:"To agree with someone about a subject or decision.", zh:"在某個議題或決定上與某人意見一致。", emoji:"👀"},
  {term:"Start off on the right foot", en:"To begin a relationship, job, or activity in a positive and successful way.", zh:"讓關係、工作或活動有正面而順利的開始。", emoji:"👟"},
  {term:"Hit it off", en:"To like someone and feel comfortable with them immediately after meeting.", zh:"與某人一見如故，初次見面就很合得來。", emoji:"🤝"},
  {term:"Strike a nerve", en:"To provoke a strong emotional reaction because a subject touches on a sensitive concern or experience.", zh:"因觸及敏感的顧慮或經歷，而引發強烈情緒反應。", emoji:"⚡"},
  {term:"It rubs me the wrong way", en:"It makes me feel annoyed, uncomfortable, or instinctively put off.", zh:"它讓我感到不舒服、惱火或本能地反感。", emoji:"🧽"},
  {term:"Get a rise out of someone", en:"To deliberately provoke an emotional, angry, or surprised reaction from someone. This is informal English.", zh:"故意挑起某人的情緒、怒氣或驚訝反應；屬非正式用語。", emoji:"🎣"},
  {term:"That really grinds my gears", en:"Used to say that something really annoys you. This is informal English.", zh:"用來表示某件事真的很惹惱自己、讓自己很煩；屬非正式用語。", emoji:"⚙️"},
  {term:"Be put on the spot", en:"To force someone into an awkward situation in which they must answer or decide immediately.", zh:"迫使某人陷入尷尬處境，必須當場回答或做決定。", emoji:"🔦"},
  {term:"Read the room", en:"To notice the mood and reactions of the people present and adjust your behavior accordingly.", zh:"察覺在場眾人的氣氛與反應，並據此調整自己的言行。", emoji:"👀"},
  {term:"Take it with a grain of salt (US) / Take it with a pinch of salt (UK)", en:"To treat a claim with skepticism rather than believe it completely. “Grain” is especially American; “pinch” is especially British.", zh:"對某項說法抱持懷疑，不完全相信。美式多用 grain，英式多用 pinch。", emoji:"🧂"},
  {term:"Split hairs", en:"To argue about extremely small or unimportant differences.", zh:"為極細微或無關緊要的差異爭論不休；吹毛求疵。", emoji:"✂️"},
  {term:"Let it slip", en:"To reveal information unintentionally, especially information that was meant to remain secret.", zh:"無意間透露原本應該保密的資訊；說溜嘴。", emoji:"🤭"},
  {term:"All walks of life", en:"People from many different social, professional, or cultural backgrounds.", zh:"來自各種社會階層、職業或文化背景的人。", emoji:"🚶"},
  {term:"Mend fences", en:"To repair a damaged relationship, especially after a disagreement.", zh:"修復受損的關係，尤其是爭執過後重修舊好。", emoji:"🪚"},
  {term:"Bury the hatchet", en:"To end a quarrel and agree to be friendly again.", zh:"結束爭執並同意重修舊好；化干戈為玉帛。", emoji:"🪓"},
  {term:"Be all ears", en:"To be ready and eager to listen carefully to what someone has to say.", zh:"準備好並非常願意仔細聽對方說話；洗耳恭聽。", emoji:"👂"},
  {term:"Ring a bell", en:"To seem familiar, even though you may not remember the exact details.", zh:"聽起來或看起來有些熟悉，但可能想不起確切細節。", emoji:"🔔"},
  {term:"A loaded question", en:"A question containing a disputed or unfair assumption, so that answering it directly appears to admit that assumption.", zh:"內含有爭議或不公平預設的問題，使人只要直接回答，就彷彿承認了該預設。", emoji:"💣"},
  {term:"A big ask", en:"Something that you ask someone to do, or hope will happen, although it will be difficult to achieve. This is informal.", zh:"要求某人完成、或希望能實現，但實際上很難達成的事情；令人為難的要求。屬非正式用語。", emoji:"🏋️"},
  {term:"A wake-up call", en:"An event that makes you recognize a problem and realize that action is needed.", zh:"使人認清問題、意識到必須採取行動的警醒事件。", emoji:"⏰"},
  {term:"A dead giveaway", en:"A clue that reveals a secret or truth very clearly, often unintentionally.", zh:"非常明顯、往往無意間洩露秘密或真相的線索。", emoji:"🔍"},
  {term:"A blessing in disguise", en:"Something that seems bad at first but later produces a good result.", zh:"起初看似壞事，後來卻帶來好結果的事情；因禍得福。", emoji:"🎁"},
  {term:"Be on the ropes", en:"To be in serious trouble and likely to fail.", zh:"陷入嚴重困境，眼看就要失敗或撐不下去。", emoji:"🥊"},
  {term:"By the same token", en:"Used to introduce another point that is true for the same reason as the previous one.", zh:"用來引出基於同一理由也同樣成立的另一點；同理。", emoji:"🪙"},
  {term:"Turn the corner", en:"For a person or situation to begin improving after a difficult period.", zh:"某人或某種情況在一段困難時期後開始好轉；渡過最壞階段。", emoji:"↪️"},
  {term:"Dodge a bullet", en:"To only just avoid something bad, harmful, or unpleasant. This is mainly US informal English.", zh:"驚險地避開壞事、傷害或令人不快的後果；主要為美式非正式用語。", emoji:"🛡️"},
  {term:"We’ll cross that bridge when we come to it", en:"To deal with a possible problem only if and when it actually happens.", zh:"等問題真的發生時再處理，不必現在先擔心。", emoji:"🌉"},
  {term:"Be up in the air", en:"To remain undecided, uncertain, or not yet arranged.", zh:"仍未決定、不確定，或尚未安排妥當。", emoji:"🎈"},
  {term:"A cautionary tale", en:"A real or fictional story whose bad outcome serves as a warning about a particular mistake, danger, or course of action.", zh:"以不良後果警告人們某種錯誤、危險或做法的真實事件或虛構故事；警世案例。", emoji:"⚠️"},
  {term:"An open-and-shut case", en:"A problem or legal case whose facts make the answer or outcome easy to prove and beyond serious doubt.", zh:"事實清楚到答案或結果很容易證明、幾乎沒有重大疑點的問題或案件。", emoji:"📂"},
  {term:"A white elephant", en:"An expensive possession or project that is difficult to maintain or dispose of and provides little value.", zh:"耗費昂貴、難以維持或脫手，實際價值卻很低的資產或計畫。", emoji:"🐘"},
  {term:"A house of cards", en:"A plan, organization, or system built on weak foundations and therefore likely to collapse.", zh:"建立在脆弱基礎上、因而很可能整體崩潰的計畫、組織或制度。", emoji:"🃏"},
  {term:"Get out of hand", en:"To become difficult or impossible to control.", zh:"情況變得難以或無法控制；失控。", emoji:"🌀"},
  {term:"Go down in flames", en:"To fail in a sudden, obvious, and often spectacular way.", zh:"以突然、明顯而且往往極其慘烈的方式失敗。", emoji:"🔥"},
  {term:"Be off the table", en:"To no longer be available for discussion, consideration, or choice.", zh:"已不再列入討論、考慮或選擇範圍。", emoji:"🚫"},
  {term:"Run out of steam", en:"To lose the energy, enthusiasm, or momentum needed to continue effectively.", zh:"失去繼續有效推進所需的精力、熱情或動能。", emoji:"🚂"},
  {term:"Weather the storm", en:"To survive a serious period of difficulty, criticism, or uncertainty.", zh:"撐過一段嚴重的困境、批評或不確定時期。", emoji:"⛈️"},
  {term:"Get cold feet", en:"To suddenly become too nervous or afraid to do something you had planned.", zh:"對原本計畫要做的事突然感到緊張或害怕而退縮。", emoji:"🥶"},
  {term:"Roll with the punches", en:"To adapt to setbacks and changing circumstances instead of being defeated by them.", zh:"隨著挫折與情勢變化調整自己，而不被它們擊倒。", emoji:"🤸"},
  {term:"Blow off steam", en:"To release strong feelings or stress through activity or conversation.", zh:"透過活動或談話釋放強烈情緒與壓力。", emoji:"💨"},
  {term:"Stand the test of time", en:"To remain effective, respected, or popular for a long period.", zh:"經過長時間考驗後，依然有效、受尊重或受歡迎。", emoji:"⌛"},
  {term:"Rise to the occasion", en:"To perform especially well when a difficult or important situation requires it.", zh:"在困難或重要時刻發揮得特別好、成功應對。", emoji:"🌟"},
  {term:"Lay the groundwork", en:"To do the preparation that makes future work or progress possible.", zh:"先做好準備，為後續工作或進展打下基礎。", emoji:"🧱"},
  {term:"A labor of love", en:"Work done because you care deeply about it rather than for financial reward.", zh:"出於深厚熱愛而做的工作，而不是為了金錢回報。", emoji:"❤️"},
  {term:"Make a mountain out of a molehill", en:"To make a small problem seem much more serious than it really is.", zh:"把小問題誇大成非常嚴重的事情；小題大作。", emoji:"🏔️"},
  {term:"Fight an uphill battle", en:"To struggle toward a goal while facing strong disadvantages or opposition.", zh:"在明顯不利或強烈反對之下，艱苦地朝目標奮鬥。", emoji:"⛰️"},
  {term:"Move heaven and earth", en:"To make every possible effort to achieve something or help someone.", zh:"為了完成某事或幫助某人而想盡一切辦法、不遺餘力。", emoji:"🌍"},
  {term:"Not add up", en:"For facts or an explanation to appear inconsistent, implausible, or incomplete.", zh:"事實或解釋看來前後不一致、不可信或有所缺漏。", emoji:"➕"},
  {term:"Be out of sorts", en:"To feel slightly unwell, unhappy, or unlike your usual self.", zh:"覺得有點不舒服、不開心，或不像平常的自己。", emoji:"🌥️"},
  {term:"Chin up", en:"To remain hopeful and confident during a difficult time.", zh:"在困難時期仍保持希望與信心；振作起來。", emoji:"🙂"},
  {term:"Pull it together", en:"To calm yourself and regain control of your emotions or behavior.", zh:"讓自己冷靜下來，重新控制情緒或行為。", emoji:"🧘"},
  {term:"A Catch-22", en:"An impossible situation in which solving one problem requires something that cannot happen until that same problem has already been solved.", zh:"陷入互相矛盾的先決條件：要解決問題就必須先做到某件事，但那件事又得等問題解決後才做得到；第 22 條軍規式困局。", emoji:"🔁"},
  {term:"Go down a rabbit hole", en:"To become deeply absorbed in a complicated or strange subject, often moving far away from your original purpose. This is informal English.", zh:"深陷於複雜或奇特的主題中，往往越鑽越深並偏離原本目的；屬非正式用語。", emoji:"🐇"},
  {term:"Get it together", en:"To become organized and begin behaving or working effectively.", zh:"把自己整理好，開始有條理而有效率地行動或工作。", emoji:"🗂️"},
  {term:"Knock/hit it out of the park", en:"To do something extremely well or achieve an outstanding result. This is informal, especially in American English.", zh:"把事情做得極為出色、取得亮眼成果；屬非正式用語，尤見於美式英語。", emoji:"⚾"},
  {term:"Carry weight", en:"To have enough importance, influence, or credibility to affect people or decisions.", zh:"具有足以影響他人或決定的重要性、影響力或可信度。", emoji:"🏋️"},
  {term:"Call the shots", en:"To be the person who controls a situation and makes the important decisions.", zh:"掌控局面並做出重要決定；說了算。", emoji:"🎬"},
  {term:"Fly under the radar", en:"To avoid attracting attention or being noticed, often deliberately.", zh:"避開注意、未被察覺，往往是刻意低調行事。", emoji:"📡"},
  {term:"Be kept in the dark", en:"To deliberately prevent someone from knowing important information about a situation.", zh:"刻意不讓某人知道某種情勢的重要資訊；把人蒙在鼓裡。", emoji:"🌑"},
  {term:"Set the record straight", en:"To correct a false account or mistaken impression by explaining what actually happened or is true.", zh:"說明實際發生的情況或真相，以糾正錯誤說法或誤解；釐清事實。", emoji:"📏"},
  {term:"Hands down", en:"Easily and without any doubt, especially when comparing people or choices.", zh:"毫無疑問、輕而易舉地，尤用於比較人或選擇。", emoji:"👇"},
  {term:"Be in good hands", en:"To be cared for or managed by someone competent and trustworthy.", zh:"由有能力且值得信任的人照顧或處理。", emoji:"🤲"},
  {term:"A hot potato", en:"A difficult or controversial issue that people do not want to handle.", zh:"棘手或具爭議、大家都不想接手處理的問題。", emoji:"🥔"},
  {term:"Get a head start", en:"To begin earlier than others and therefore gain an advantage.", zh:"比別人更早開始，因而取得優勢。", emoji:"🏁"},
  {term:"Close ranks", en:"For members of a group to unite and support one another, especially when criticized or threatened.", zh:"團體成員在遭受批評或威脅時團結一致、彼此支持。", emoji:"🛡️"},
  {term:"Take the gloves off", en:"To stop being restrained or polite and begin competing, arguing, or attacking much more aggressively.", zh:"不再克制或客氣，開始更強硬地競爭、爭辯或攻擊。", emoji:"🥊"},
  {term:"Tip the balance/scales", en:"To provide the decisive influence that makes one outcome, side, or choice more likely to prevail.", zh:"帶來決定性的影響，使某個結果、陣營或選擇更可能勝出。", emoji:"⚖️"},
  {term:"Nip it in the bud", en:"To stop a problem at an early stage before it becomes more serious.", zh:"在問題剛出現時就加以制止，避免它變得更嚴重。", emoji:"🌱"},
  {term:"Tie up loose ends", en:"To finish the remaining small tasks or settle unresolved details.", zh:"完成剩餘的小事，處理尚未解決的細節。", emoji:"🪢"},
  {term:"Jump the gun", en:"To act too soon, before the proper time or before sufficient information is available.", zh:"在適當時機到來或資訊充分之前就過早行動；搶跑。", emoji:"🔫"},
  {term:"Set the wheels in motion", en:"To take the action that causes a process or series of events to begin.", zh:"採取行動，讓某個流程或一連串事件開始運轉。", emoji:"⚙️"},
  {term:"Hit the ground running", en:"To begin a new activity or role immediately with energy and effectiveness.", zh:"一進入新活動或新職務就立刻充滿幹勁、有效率地展開工作。", emoji:"🏃"},
  {term:"Fall into place", en:"For the parts of a situation or plan to begin working together or becoming clear.", zh:"情勢或計畫的各部分開始配合起來，或逐漸變得清楚。", emoji:"🧩"},
  {term:"A canary in the coal mine", en:"An early indicator that warns of a wider, more serious danger or problem.", zh:"預警更廣泛、更嚴重危險或問題的早期指標。", emoji:"🐤"},
  {term:"The tip of the iceberg", en:"The small visible part of a problem or situation whose much larger part remains hidden.", zh:"問題或情況中浮出水面的極小部分，背後還隱藏著更龐大的部分。", emoji:"🧊"},
  {term:"An Achilles’ heel", en:"A crucial weakness in someone or something that is otherwise strong.", zh:"某人或某事物整體雖強，卻存在的一項致命弱點。", emoji:"🦶"},
  {term:"A fault line", en:"A deep underlying division or weakness that could cause serious conflict or failure.", zh:"可能引發嚴重衝突或失敗的深層分歧或弱點。", emoji:"🪨"},
  {term:"A sticking point", en:"A particular issue that prevents an agreement, decision, or process from moving forward.", zh:"阻礙協議、決定或流程繼續推進的特定爭點。", emoji:"📍"},
  {term:"Take heart", en:"To become more hopeful or confident because of something encouraging.", zh:"因受到鼓舞而重新產生希望或信心。", emoji:"💖"},
  {term:"A perfect storm", en:"An unusually bad situation created by several harmful factors occurring together.", zh:"多項不利因素同時出現，合力造成的異常惡劣局面。", emoji:"🌪️"},
  {term:"A powder keg", en:"A highly tense or unstable situation that could suddenly become violent or disastrous.", zh:"高度緊張或不穩定、隨時可能突然爆發暴力或災難的局勢；火藥桶。", emoji:"🧨"},
  {term:"A moving target", en:"An objective, standard, or problem that keeps changing and is therefore difficult to define or achieve.", zh:"不斷改變、因而難以界定或達成的目標、標準或問題。", emoji:"🎯"},
  {term:"A wild card", en:"An unpredictable person or factor that could affect the outcome of a situation in an unexpected way.", zh:"可能以意想不到的方式影響結果、難以預測的人或因素；變數。", emoji:"🃏"},
  {term:"A minefield", en:"A situation or subject that is very complicated and full of hidden problems or dangers.", zh:"非常複雜、充滿隱藏問題或危險的情勢或議題；處處是地雷。", emoji:"💣"},
  {term:"Wear your heart on your sleeve", en:"To show your emotions openly instead of hiding them.", zh:"不隱藏情緒，坦率地把感受表現出來。", emoji:"👕"},
  {term:"The missing link", en:"The absent piece of information, evidence, or connection needed to complete an explanation or solve a problem.", zh:"完成解釋或解決問題所欠缺的資訊、證據或關聯；缺失的一環。", emoji:"🔗"},
  {term:"A litmus test", en:"A decisive test that reveals the true quality, attitude, or acceptability of someone or something.", zh:"能顯示某人或某事物真實品質、態度或可接受程度的關鍵考驗。", emoji:"🧪"},
  {term:"The holy grail", en:"A goal or discovery that is intensely desired but extremely difficult to achieve or obtain.", zh:"人們極度渴望、卻非常難以達成或取得的目標或發現；夢寐以求的聖杯。", emoji:"🏆"},
  {term:"Compare apples and oranges", en:"To compare two things that are too different for the comparison to be fair or useful.", zh:"比較兩件差異過大的事物，以致比較並不公平或沒有實際意義。", emoji:"🍎"},
  {term:"A chicken-and-egg situation", en:"A situation in which it is impossible to tell which of two things came first or which one caused the other.", zh:"無法判斷兩件事何者先出現，或究竟是誰導致誰的情況；雞生蛋、蛋生雞的因果難題。", emoji:"🥚"},
  {term:"Clutch at straws", en:"To try anything that might improve a difficult situation, even when it has very little chance of working.", zh:"在困境中不放過任何可能有幫助的方法，即使成功機會極低；抓住救命稻草。", emoji:"🌾"},
  {term:"A vicious circle (UK) / vicious cycle (US)", en:"A continuing harmful situation in which one problem causes another, which then makes the original problem worse.", zh:"一個問題引發另一個問題，而後者又反過來使原問題惡化的持續性困局；惡性循環。", emoji:"🔄"},
  {term:"Food for thought", en:"An idea or piece of information that deserves careful consideration.", zh:"值得仔細思考的想法或資訊；發人深省的內容。", emoji:"🍽️"},
  {term:"A red herring", en:"An irrelevant point or piece of information introduced to distract attention from the real issue.", zh:"為轉移人們對真正問題的注意，而拋出的無關論點或資訊；煙霧彈。", emoji:"🐟"},
  {term:"A silver bullet", en:"A simple solution that is expected to solve a complicated problem completely, especially when people doubt that such a solution exists.", zh:"被期待能一舉徹底解決複雜問題的簡單方案，尤常用來表示這種萬靈丹其實並不存在。", emoji:"🥈"},
  {term:"Jump through hoops", en:"To have to complete many difficult or unnecessary requirements before being allowed to get or do something.", zh:"必須先完成許多困難或不必要的要求，才獲准取得或做某件事。", emoji:"🎪"},
  {term:"Smoke and mirrors", en:"A deceptive presentation or explanation intended to hide the truth or disguise a lack of real substance.", zh:"用來掩蓋真相或實質空洞的欺瞞性包裝與說法；障眼法。", emoji:"🪞"},
  {term:"A Trojan horse", en:"Someone or something that appears harmless or helpful but is intended to enter, undermine, or damage from within.", zh:"表面無害或有益，實際目的是混入內部並加以破壞的人或事物；特洛伊木馬。", emoji:"🐴"},
  {term:"Test the waters", en:"To try something cautiously in order to learn how people will react or whether it will succeed.", zh:"先小心嘗試，以了解他人的反應或事情是否可行。", emoji:"🌊"},
  {term:"A smoking gun", en:"A piece of evidence that clearly proves who is responsible for a crime or wrongdoing.", zh:"能明確證明誰應為犯罪或不當行為負責的關鍵證據。", emoji:"🔫"},
  {term:"The elephant in the room", en:"An obvious and important problem that everyone avoids discussing.", zh:"明明存在且很重要，大家卻刻意避而不談的問題。", emoji:"🐘"},
  {term:"Bite the bullet", en:"To force yourself to do or accept something difficult or unpleasant.", zh:"鼓起勇氣去做或接受困難、令人不快的事情。", emoji:"🦷"},
  {term:"Be firing on all cylinders", en:"To be operating or performing at full power and effectiveness.", zh:"以全部實力高效運作或表現；火力全開。", emoji:"⚙️"},
  {term:"Be on a roll", en:"To be enjoying a period of repeated success or good luck. This is informal.", zh:"正處於接連成功或好運不斷的時期；屬非正式用語。", emoji:"🎳"},
  {term:"Red tape", en:"Excessive official rules and procedures that cause unnecessary delay.", zh:"造成不必要延誤的繁複官方規定與程序；官僚繁文縟節。", emoji:"🧵"},
  {term:"The ball is in your court", en:"It is now your responsibility to make the next decision or take the next action.", zh:"現在輪到你做出下一個決定或採取下一步行動。", emoji:"🎾"},
  {term:"Jump at the chance", en:"To accept an opportunity eagerly and immediately.", zh:"非常積極而且毫不猶豫地把握機會。", emoji:"🦘"},
  {term:"Stick the landing", en:"To finish a task, performance, or story successfully, especially after a difficult build-up. This is American informal English.", zh:"尤其在前段過程不容易之後，成功而漂亮地完成任務、表演或故事收尾；美式非正式用語。", emoji:"🤸"},
  {term:"A tower of strength", en:"To give someone strong emotional support and dependable help during a difficult time.", zh:"在艱難時期給予強大而可靠的情感支持與幫助。", emoji:"🗼"},
  {term:"Run like clockwork", en:"To happen or operate smoothly, regularly, and exactly as planned.", zh:"順暢而規律地運作，完全按計畫進行。", emoji:"🕰️"},
  {term:"In the nick of time", en:"Just before it would have been too late.", zh:"恰好在來不及之前的最後一刻。", emoji:"⏱️"},
  {term:"Push the envelope", en:"To extend the accepted limits of what is possible, permitted, or conventional.", zh:"突破人們對可能性、許可範圍或慣例的既有限制。", emoji:"✉️"},
  {term:"Around the clock", en:"All day and all night without stopping.", zh:"日夜不停、二十四小時持續進行。", emoji:"🕐"},
  {term:"Lose my train of thought", en:"To forget what you were saying or thinking before you finished.", zh:"話還沒說完或思緒尚未完成，就忘了自己原本要說或想什麼。", emoji:"🚂"},
  {term:"Warts and all", en:"Including all faults and unpleasant facts, without trying to hide them.", zh:"連缺點與難看的事實也全部呈現，毫不遮掩。", emoji:"🪞"},
  {term:"A flash in the pan", en:"Someone or something that initially seems promising or successful but quickly disappoints or disappears.", zh:"起初看似很有前途或成功，卻很快令人失望或消失的人或事物；曇花一現。", emoji:"✨"},
  {term:"Speak volumes", en:"To reveal or communicate a great deal without anything needing to be stated explicitly.", zh:"不必明說就透露或傳達了大量訊息；不言自明。", emoji:"📚"},
  {term:"Fall on deaf ears", en:"For advice, warnings, requests, or appeals to be ignored.", zh:"建議、警告、請求或呼籲遭到忽視，沒有人願意聽。", emoji:"🙉"},
  {term:"Tempt fate", en:"To take an unnecessary risk or behave as if a good situation cannot go wrong.", zh:"冒不必要的風險，或彷彿好情況絕不會出錯般行事。", emoji:"🎰"},
  {term:"A wild goose chase", en:"A search or pursuit that wastes time because it is unlikely to succeed.", zh:"白忙一場、注定沒有結果的追查或尋找。", emoji:"🪿"},
  {term:"The writing on the wall", en:"Clear signs that an unpleasant outcome, failure, or ending is approaching.", zh:"已經很明顯、預示失敗或結束即將到來的徵兆。", emoji:"🧱"},
  {term:"A needle in a haystack", en:"Someone or something extremely difficult to find among a very large number of possibilities.", zh:"幾乎不可能從大量事物中找到的人或物。", emoji:"🪡"},
  {term:"A ticking time bomb", en:"A dangerous problem that may suddenly cause serious harm even though it has not done so yet.", zh:"暫時沒事，卻隨時可能爆發的嚴重隱患。", emoji:"💣"},
  {term:"A fork in the road", en:"A point at which you must choose between different directions or courses of action.", zh:"必須選擇不同方向的關鍵時刻。", emoji:"🛤️"},
  {term:"A tough nut to crack", en:"A person, problem, or task that is difficult to understand, solve, or deal with.", zh:"很難理解、解決或應付的人事物。", emoji:"🌰"},
  {term:"A tall order", en:"A request or task that will be very difficult to accomplish.", zh:"很難做到的要求或任務。", emoji:"📋"},
  {term:"A close call", en:"A situation in which danger, failure, or another bad outcome is only narrowly avoided.", zh:"差一點就出事或失敗的驚險情況。", emoji:"😮‍💨"},
  {term:"The lion’s share", en:"The largest part of something, much greater than any other share.", zh:"全部之中最大、遠多於其他部分的一份。", emoji:"🦁"},
  {term:"A downward spiral", en:"A process in which problems reinforce one another and make a situation steadily worse.", zh:"情況彼此加劇、持續向下惡化的循環。", emoji:"🌀"},
  {term:"A rough patch", en:"A temporary period of difficulty or trouble.", zh:"一段暫時不順、難熬的時期。", emoji:"🩹"},
  {term:"A lucky break", en:"An unexpected opportunity or event that improves your situation.", zh:"意外得到的好機會或幸運轉機。", emoji:"🍀"},
  {term:"A stroke of luck", en:"A sudden and unexpected piece of good fortune.", zh:"突然而來的一次好運。", emoji:"✨"},
  {term:"The luck of the draw", en:"A result determined by chance rather than skill or choice.", zh:"結果取決於隨機分配或運氣。", emoji:"🎲"},
  {term:"Out of the woods", en:"Past the most dangerous or difficult stage of a situation.", zh:"已經脫離最危險或最困難的階段。", emoji:"🌲"},
  {term:"Sink or swim", en:"To succeed or fail through your own efforts when no help or easier option is available.", zh:"沒有退路，只能靠自己成功或失敗。", emoji:"🏊"},
  {term:"Turn the tide", en:"To reverse an unfavorable situation or trend.", zh:"扭轉原本不利的局勢或趨勢。", emoji:"🌊"},
  {term:"Ride the wave", en:"To benefit from and continue with a growing trend, movement, or period of success.", zh:"順著正在上升的趨勢或氣勢前進。", emoji:"🏄"},
  {term:"Make a splash", en:"To attract a great deal of attention or make a strong impression.", zh:"引起明顯注意並留下強烈印象。", emoji:"💦"},
  {term:"Take the plunge", en:"To decide to do something important or difficult after a period of hesitation.", zh:"下定決心踏出原本猶豫的一大步。", emoji:"🤿"},
  {term:"Blaze a trail", en:"To be the first to develop or follow a new path, method, or area of activity.", zh:"開創一條別人尚未走過的新路。", emoji:"🥾"},
  {term:"Break new ground", en:"To introduce new ideas or methods, or make progress in an unexplored area.", zh:"開拓新的領域、方法或可能性。", emoji:"🧭"},
  {term:"Bark up the wrong tree", en:"To blame the wrong person or pursue a mistaken explanation or course of action.", zh:"找錯對象、怪錯人或朝錯誤方向追查。", emoji:"🌳"},
  {term:"A white whale", en:"A goal that becomes an intense, long-term obsession but remains difficult to achieve.", zh:"長期執著追尋、卻一直難以得到的目標。", emoji:"🐋"},
  {term:"Like herding cats", en:"Used to describe the difficulty of organizing people who act independently and resist coordination.", zh:"要協調一群各做各的對象，困難又混亂。", emoji:"🐈"},
  {term:"A pipe dream", en:"A plan or hope that is extremely unlikely to become reality.", zh:"幾乎不可能實現的幻想或計畫。", emoji:"💭"},
  {term:"Few and far between", en:"Rare and not occurring or appearing very often.", zh:"數量極少，而且彼此相隔很久或很遠。", emoji:"🔭"},
  {term:"A dime a dozen", en:"Very common and therefore not special or valuable. This is informal US English.", zh:"多到很普通、不稀奇也不特別有價值。", emoji:"🪙"},
  {term:"Barely scratch the surface", en:"To deal with or learn only a very small part of a much larger subject or problem.", zh:"只觸及表層，離完整了解還很遠。", emoji:"🔍"},
  {term:"A bottomless pit", en:"Something that seems to consume an unlimited amount of money, time, or effort.", zh:"像無底洞般不斷吞噬時間、金錢或精力的事物。", emoji:"🕳️"},
  {term:"A bull in a china shop", en:"A person who behaves clumsily or carelessly in a situation requiring tact and care.", zh:"在需要細膩處理的情況中顯得笨拙又容易闖禍的人。", emoji:"🐂"},
  {term:"Let sleeping dogs lie", en:"To avoid interfering with or discussing a problem that is currently causing no trouble.", zh:"別重新提起或干預已經平靜下來的問題。", emoji:"🐕"},
  {term:"A lightbulb moment", en:"A sudden moment of understanding or realization.", zh:"突然想通、找到答案的瞬間。", emoji:"💡"},
  {term:"Pick up the pieces", en:"To begin recovering and rebuilding after a failure, loss, or period of disorder.", zh:"在失敗、打擊或混亂後開始收拾並重建生活或局面。", emoji:"🧩"},
  {term:"Turn over a new leaf", en:"To change your behavior and begin acting in a better way.", zh:"改變舊習慣，開始採取更好的做法。", emoji:"🍃"},
  {term:"Come full circle", en:"To return to the original position, idea, or situation after a series of changes.", zh:"繞了一圈後回到最初的位置、想法或狀態。", emoji:"🔄"},
  {term:"Reinvent the wheel", en:"To waste effort creating a method or solution that already exists.", zh:"白費力氣重做一套早已存在的解法。", emoji:"🛞"},
  {term:"The new kid on the block", en:"A person, organization, or product newly arrived in a group, area, or market.", zh:"剛加入某個領域、群體或市場的新成員。", emoji:"🆕"},
  {term:"Second nature", en:"A skill or behavior so familiar that it can be done almost automatically.", zh:"熟練到幾乎不用思考就能自然做到。", emoji:"🧠"},
  {term:"Like riding a bike", en:"Used to say that a learned skill is easy to recover even after a long time without practice.", zh:"一旦學會，即使久未練習也很容易恢復。", emoji:"🚲"},
  {term:"In the groove", en:"Performing smoothly and confidently because you have found a good rhythm.", zh:"已進入順手、有節奏而表現良好的狀態。", emoji:"🎶"},
  {term:"Bring my A-game", en:"To perform at the highest level you are capable of.", zh:"拿出自己最佳的能力與表現。", emoji:"🅰️"},
  {term:"Pull it off", en:"To succeed in doing something difficult or unexpected.", zh:"成功辦成原本看來很困難的事。", emoji:"🎯"},
  {term:"A saving grace", en:"A good quality that prevents someone or something from being completely bad or unacceptable.", zh:"讓整體不至於太糟、仍值得肯定的一個優點。", emoji:"✨"},
  {term:"An escape hatch", en:"A way to leave, avoid, or end a difficult or unfavorable situation.", zh:"在局面不利時可退出或脫身的方法。", emoji:"🚪"},
  {term:"Elbow room", en:"Enough space or freedom to move, act, or make decisions.", zh:"可以自由活動、決定或發揮的空間。", emoji:"↔️"},
  {term:"A margin for error", en:"An amount of room for small mistakes without causing failure.", zh:"允許出現小錯誤而不致失敗的餘地。", emoji:"📏"},
  {term:"Let it sink in", en:"To allow time for information or an event to be fully understood or emotionally absorbed.", zh:"給自己時間慢慢理解或消化一件事。", emoji:"🫧"},
  {term:"Mull it over", en:"To think carefully about something for a period of time before deciding.", zh:"花時間反覆思考後再決定。", emoji:"🤔"},
  {term:"For what it’s worth", en:"Used before offering an opinion that may or may not be useful or valued.", zh:"委婉提出一個不確定對方是否需要的看法。", emoji:"💬"},
  {term:"Straight from the horse’s mouth", en:"Directly from the person who knows the facts or is most closely involved.", zh:"直接來自當事人或第一手來源的消息。", emoji:"🐴"},
  {term:"The inside scoop", en:"Private or little-known information from someone with direct knowledge. This is informal English.", zh:"外界通常不知道的內幕或第一手消息。", emoji:"🥄"},
  {term:"My mind went blank", en:"Used to say that you suddenly became unable to remember or think of anything.", zh:"腦中突然一片空白，完全想不起來或說不出話。", emoji:"⬜"},
  {term:"On the tip of my tongue", en:"Almost remembered or ready to be said, but temporarily impossible to recall exactly.", zh:"明明知道，卻一時說不出那個詞或答案。", emoji:"👅"},
  {term:"It slipped my mind", en:"Used to say that you forgot something you knew or intended to do.", zh:"原本知道或打算做，卻一時忘記了。", emoji:"🫥"},
  {term:"A blast from the past", en:"A person or thing from the past that returns unexpectedly and brings back memories.", zh:"突然重新出現、勾起回憶的舊人舊事物。", emoji:"📼"},
  {term:"Between a rock and a hard place", en:"In a situation where you must choose between two equally difficult or unpleasant options.", zh:"夾在兩個都不理想的選擇之間。", emoji:"🪨"},
  {term:"In a pickle", en:"In a difficult or troublesome situation. This is informal and slightly humorous.", zh:"陷入麻煩或難以處理的處境；語氣較俏皮。", emoji:"🥒"},
];
